version: '3'
services:
  backend-development:
    build:
      context: ../
      dockerfile: docker/development.Dockerfile
      args:
        port: ${PORT}
    env_file:
      - ../.env
    restart: always
    ports:
      - '${PORT}:${PORT}'
    environment:
      WAIT_HOSTS: database-development:27017
  database-development:
    build: ./mongo-with-seeds
    env_file:
      - ../.env
    volumes:
      - './${MONGO_DEVELOPMENT_DATA_DIR}:/data/db'
    expose:
      - 27017
    command: 'mongod --smallfiles --logpath=${MONGO_LOG_FILE}'
